version: "3.3"

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src:/app    
    ports:
      - "80:80"
    networks:
      - elastic

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src:/app
    networks:
      - elastic

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./src:/app
    networks:
      - elastic

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - elastic

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=default
      - MYSQL_PASSWORD=default
    ports:
      - "3306:3306"
    networks:
      - elastic

  elasticsearch:
    build:
      context: ./docker/elasticsearch
    volumes:
      - ./docker/databases/elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    depends_on:
      - php-fpm
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

