version: "3.3"

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/app

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src:/app